/**
 * Release gate: the packed tarball, installed into a real consumer project,
 * completes the workflow the product promises.
 *
 * Everything else in this repo tests source. This tests what a user actually
 * receives: `npm pack`, `npm install <tarball>`, then the documented flow —
 * install the skill, explore the app, turn an element into a durable selector,
 * author an ordinary test, watch it fail, diagnose the failure from evidence,
 * fix it with an explicit source diff, and see it pass.
 *
 * Deterministic and model-free by construction. The failure is a fixture that
 * POSTs to an endpoint the static server does not serve, so it fails the same
 * way every run, and the "fix" is a source edit a reviewer could read.
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
  existsSync,
  statSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { EXAMPLES_BASE_URL } from '../utils';

const REPO = resolve(__dirname, '..', '..');

/**
 * Unix socket paths are capped near 104 bytes on macOS, and the system temp
 * directory is already long. A short fixed path keeps the daemon startable.
 */
const SOCKET = '/tmp/cdrel.sock';
const PIDFILE = '/tmp/cdrel.pid';

let consumer: string;
let cli: string;
let env: NodeJS.ProcessEnv;

/** Content a consumer already had, which the installer must never touch. */
const PREEXISTING: Record<string, string> = {
  'AGENTS.md': '# My agents\n\nDo not edit this file.\n',
  'CLAUDE.md': '# Claude instructions\n\nMine.\n',
  '.codex/config.toml': '[mcp_servers.other]\ncommand = "something"\n',
  '.cursor/rules/house.mdc': 'house rules\n',
};

function hashOf(path: string): string {
  return createHash('sha256').update(readFileSync(path)).digest('hex');
}

/** Run the packed CLI in the consumer project. Returns stdout. */
function run(args: string[], opts: { allowFailure?: boolean } = {}): string {
  try {
    return execFileSync('node', [cli, ...args], {
      cwd: consumer,
      env,
      encoding: 'utf8',
      timeout: 120_000,
    });
  } catch (err) {
    const e = err as { stdout?: string; stderr?: string; status?: number };
    if (opts.allowFailure) return `${e.stdout ?? ''}${e.stderr ?? ''}`;
    throw new Error(
      `craftdriver ${args.join(' ')} failed (exit ${e.status}):\n${e.stdout ?? ''}\n${e.stderr ?? ''}`,
    );
  }
}

/** Parse the JSON envelope the CLI writes when stdout is not a TTY. */
function json(args: string[]): Record<string, unknown> {
  const out = run(args).trim().split('\n').filter(Boolean);
  const parsed = JSON.parse(out[out.length - 1]) as { ok: boolean; result: Record<string, unknown> };
  return parsed.result;
}

describe('packed CLI and skill', () => {
  beforeAll(() => {
    const workspace = mkdtempSync(join(tmpdir(), 'craftdriver-release-'));
    consumer = join(workspace, 'consumer');
    mkdirSync(consumer, { recursive: true });

    // 1. The actual artifact a user installs.
    const packed = execFileSync('npm', ['pack', '--pack-destination', workspace], {
      cwd: REPO,
      encoding: 'utf8',
      timeout: 300_000,
    })
      .trim()
      .split('\n')
      .pop() as string;
    const tarball = join(workspace, packed);

    writeFileSync(
      join(consumer, 'package.json'),
      JSON.stringify({ name: 'consumer', version: '1.0.0', private: true }, null, 2),
    );

    // Pre-existing files the installer is forbidden from touching.
    for (const [rel, content] of Object.entries(PREEXISTING)) {
      const target = join(consumer, rel);
      mkdirSync(resolve(target, '..'), { recursive: true });
      writeFileSync(target, content);
    }

    execFileSync('npm', ['install', tarball, '--no-audit', '--no-fund'], {
      cwd: consumer,
      encoding: 'utf8',
      timeout: 600_000,
    });

    cli = join(consumer, 'node_modules', 'craftdriver', 'bin', 'craftdriver.mjs');
    env = {
      ...process.env,
      HEADLESS: 'true',
      CRAFTDRIVER_SOCKET: SOCKET,
      CRAFTDRIVER_PID: PIDFILE,
      CRAFTDRIVER_STATE_DIR: join(consumer, '.craftdriver', 'state'),
      CRAFTDRIVER_TRACE_DIR: join(consumer, '.craftdriver', 'traces'),
    };
  }, 900_000);

  afterAll(() => {
    try {
      run(['daemon', 'stop'], { allowFailure: true });
    } catch {
      /* already down */
    }
    rmSync(resolve(consumer, '..'), { recursive: true, force: true });
    rmSync(SOCKET, { force: true });
    rmSync(PIDFILE, { force: true });
  });

  it('ships a working binary', () => {
    expect(existsSync(cli)).toBe(true);
    expect(run(['--help'])).toContain('craftdriver');
  });

  it('installs the skill without touching any instruction file', () => {
    const before = Object.fromEntries(
      Object.keys(PREEXISTING).map((rel) => [rel, hashOf(join(consumer, rel))]),
    );

    run(['init', 'codex']);

    const skillDir = join(consumer, '.agents', 'skills', 'craftdriver');
    expect(existsSync(join(skillDir, 'SKILL.md'))).toBe(true);
    expect(existsSync(join(skillDir, 'workflow.md'))).toBe(true);

    // The manifest must describe exactly what was written.
    const manifest = JSON.parse(
      readFileSync(join(skillDir, '.craftdriver-manifest.json'), 'utf8'),
    ) as { files: Record<string, string> };
    for (const [rel, digest] of Object.entries(manifest.files)) {
      const written = createHash('sha256').update(readFileSync(join(skillDir, rel))).digest('hex');
      expect(written).toBe(digest);
    }

    // The whole point of the installer's contract.
    for (const [rel, digest] of Object.entries(before)) {
      expect(hashOf(join(consumer, rel))).toBe(digest);
    }
  }, 120_000);

  it('refuses to overwrite skill content a user has edited', () => {
    const skillFile = join(consumer, '.agents', 'skills', 'craftdriver', 'workflow.md');
    const mine = '# mine now\n';
    writeFileSync(skillFile, mine);

    const output = run(['init', 'codex'], { allowFailure: true });
    expect(readFileSync(skillFile, 'utf8')).toBe(mine);
    expect(output).toMatch(/edit|modif|refus/i);
  }, 120_000);

  it('explores the application and yields a durable selector, never a ref', () => {
    run(['go', `${EXAMPLES_BASE_URL}/agent-debug.html`]);

    const snapshot = json(['snapshot']);
    expect((snapshot.lines as string[]).join('\n')).toMatch(/Place order/);

    const locators = json(['locators', '#place-order']);
    const best = locators.best as string;
    expect(best).toBeTruthy();
    // What goes into a committed test must never be exploration state.
    expect(best).not.toMatch(/ref=/);
    expect(JSON.stringify(locators.candidates)).not.toContain('ref=');
  }, 180_000);

  it('keeps named sessions and tabs isolated', () => {
    run(['go', `${EXAMPLES_BASE_URL}/login.html`, '--session', 'alpha']);
    run(['go', `${EXAMPLES_BASE_URL}/agent-debug.html`, '--session', 'beta']);

    expect(json(['status', '--session', 'alpha']).activeUrl as string).toContain('login.html');
    expect(json(['status', '--session', 'beta']).activeUrl as string).toContain('agent-debug.html');

    const sessions = json(['session', 'list']);
    expect(sessions.count as number).toBeGreaterThanOrEqual(2);

    run(['session', 'close', 'alpha']);
    run(['session', 'close', 'beta']);
  }, 300_000);

  it('saves and restores a login without printing a secret', () => {
    run(['go', `${EXAMPLES_BASE_URL}/login.html`]);
    run(['fill', '#username', 'releaseuser']);
    run(['fill', '#password', 'hunter2']);
    run(['click', '#submit']);

    const saved = run(['state', 'save', 'release']);
    expect(saved).not.toContain('hunter2');
    expect(saved).not.toContain('releaseuser');

    const file = join(consumer, '.craftdriver', 'state', 'release.json');
    expect(existsSync(file)).toBe(true);
    if (process.platform !== 'win32') {
      expect(statSync(file).mode & 0o777).toBe(0o600);
    }

    // Restoring onto a blank page would silently drop origin-scoped storage,
    // so the CLI refuses it and names the origin.
    run(['quit']);
    const refused = run(['state', 'load', 'release'], { allowFailure: true });
    expect(refused).toMatch(/origin/i);

    run(['go', `${EXAMPLES_BASE_URL}/login.html`]);
    run(['state', 'load', 'release']);
    run(['reload']);
    expect(json(['text', '#welcome']).text as string).toContain('releaseuser');
  }, 300_000);

  it('diagnoses a failure the page will not explain', () => {
    run(['go', `${EXAMPLES_BASE_URL}/agent-debug.html`]);
    run(['logs', 'clear']);
    run(['click', 'role=button[name=Place order]']);
    run(['logs', 'wait', '--kind', 'error', '--timeout', '10000']);

    // The page says only that something went wrong...
    const shown = json(['text', '#status']).text as string;
    expect(shown).toContain('Something went wrong');
    expect(shown).not.toMatch(/\b4\d\d\b/);

    // ...and the journal says exactly what.
    const errors = json(['logs', '--kind', 'error']);
    const text = JSON.stringify(errors.entries);
    expect(text).toMatch(/checkout failed: HTTP 4\d\d/);
    expect(text).toContain('/api/checkout');
  }, 300_000);

  it('authors a test that fails, is diagnosed, and is fixed by an explicit diff', () => {
    // Step 5 of the shipped workflow: an ordinary test using the durable
    // selector found above, written against the public library API.
    const testPath = join(consumer, 'checkout.test.mjs');
    const failing = `
import assert from 'node:assert/strict';
import { Browser, By } from 'craftdriver';

const browser = await Browser.launch({ browserName: 'chrome' });
try {
  await browser.navigateTo('${EXAMPLES_BASE_URL}/agent-debug.html');
  await browser.locator(By.role('button', { name: 'Place order' })).click();
  // Auto-waiting assertion: the status starts as "Placing order…" and settles
  // once the request resolves, so a bare read would race the fetch.
  await browser.expect('#status').toContainText('confirmed', { timeout: 10000 });
} finally {
  await browser.quit();
}
`;
    writeFileSync(testPath, failing);

    // It fails, because the endpoint really is broken.
    let failure = '';
    try {
      execFileSync('node', [testPath], { cwd: consumer, env, encoding: 'utf8', timeout: 180_000 });
      throw new Error('expected the authored test to fail');
    } catch (err) {
      const e = err as { stdout?: string; stderr?: string };
      failure = `${e.stdout ?? ''}${e.stderr ?? ''}`;
    }
    expect(failure).toMatch(/Something went wrong|EXPECT_MISMATCH|confirmed/);

    // The fix is a source diff a reviewer can read — not a retry, not a sleep,
    // not a weaker assertion.
    const fixed = failing.replace(
      "  await browser.navigateTo(",
      `  await browser.network.mock('**/api/checkout*', {
    status: 200,
    headers: { 'content-type': 'application/json' },
    body: '{"orderId":"A-1001"}',
  });
  await browser.navigateTo(`,
    );
    expect(fixed).not.toBe(failing);
    writeFileSync(testPath, fixed);

    // Same assertion, now passing.
    execFileSync('node', [testPath], { cwd: consumer, env, encoding: 'utf8', timeout: 180_000 });

    const committed = readFileSync(testPath, 'utf8');
    expect(committed).not.toMatch(/ref=/);
    expect(committed).toMatch(/By\.role/);
  }, 600_000);

  it('shuts down leaving no stale socket, pid, or session', () => {
    const stopped = run(['daemon', 'stop'], { allowFailure: true });
    expect(existsSync(SOCKET), `socket after stop; stop said: ${stopped}`).toBe(false);
    expect(existsSync(PIDFILE), `pid after stop; stop said: ${stopped}`).toBe(false);

    // A later command relaunches cleanly rather than inheriting old state.
    const status = json(['status']);
    expect(status).toBeTruthy();
    run(['daemon', 'stop'], { allowFailure: true });
  }, 300_000);

  it('advertises only what actually shipped', () => {
    const skillDir = join(consumer, '.agents', 'skills', 'craftdriver');
    const cliDoc = readFileSync(join(skillDir, 'cli.md'), 'utf8');
    const help = run(['--help']);

    // Every command the shipped skill teaches must exist in the shipped
    // binary. Guidance naming a command the CLI lacks is worse than none.
    for (const command of ['snapshot', 'locators', 'logs', 'state', 'trace', 'mock', 'page']) {
      expect(cliDoc).toContain(command);
      expect(help).toContain(command);
    }
  }, 120_000);

  it('packs no stray files', () => {
    const installed = join(consumer, 'node_modules', 'craftdriver');
    const entries = readdirSync(installed);
    // The published surface is deliberately narrow.
    expect(entries).toContain('dist');
    expect(entries).toContain('bin');
    expect(entries).toContain('skills');
    expect(entries).not.toContain('src');
    expect(entries).not.toContain('tests');
    expect(entries).not.toContain('plans');
  });
});
